export enum TXN_FORM_ACTION_TYPES {
  CHANGE_PAYEE = 'CHANGE_PAYEE',
  CHANGE_CATEGORY = 'CHANGE_CATEGORY',
  CHANGE_OUTCOME = 'CHANGE_OUTCOME',
  CHANGE_INCOME = 'CHANGE_INCOME',
  CHANGE_DATE = 'CHANGE_DATE',
}
